insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',1);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',1);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',2);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',2);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',3);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',3);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',4);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',4);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',5);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',5);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',6);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',6);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',7);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',7);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',8);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',8);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',9);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',9);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',10);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',10);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',11);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',11);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',12);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',12);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',13);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',13);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',14);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',14);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',15);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',15);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',16);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',16);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',17);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',17);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',18);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',18);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',19);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',19);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',20);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',20);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',21);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',21);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',22);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',22);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',23);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',23);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',24);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',24);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',25);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',25);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',26);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',26);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',27);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',27);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',28);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',28);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',29);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',29);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',30);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',30);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',31);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',31);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',32);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',32);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',33);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',33);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',34);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',34);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',35);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',35);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',36);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',36);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',37);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',37);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',38);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',38);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',39);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',39);

insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (1,'Licores y Bebidas',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (2,'Productos de limpieza Personal',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (3,'Tecnologia',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (4,'Ropa',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (5,'Alimentos',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (6,'Chucherias',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (7,'Congelados',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (8,'Charcuteria',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (9,'Carniceria',40);
insert into pasillo (pas_numero,pas_descripcion,pas_fk_tienda) values (10,'Detergentes',40);