insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('MarketTextil','Distribuidos de lenceria, toallas, almohadas y colchones',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('TecnoMarca','Distribuidos de televisores y equipos de sonido',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Chocolatieres','Distribuidos de chocolates',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('FishMarket','Distribuidos de frutos del mar congelados y empacados',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Aves','Distribuidos de pollo y pavo, congelados y empacados al vacio',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('DelicatesesMarket','Distribuidos de Distribuidos de embutidos y especialidades derivados del pollo',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Ofis','Distribuidos de material de oficina',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('MuebleSoft','Distribuidos de mobiliario para oficina',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('MuebleHogar','Distribuidos de muebles para el hogar',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('CarMarket','Distribuidos de cuachos para vehiculos',true);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('IndustrialMarket','Distribuidos de articulos de limpieza',true);

insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Colgate','Distribuidos de pasta dental y cepillos de dientes',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Polar','Distribuidos de alimentos',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Mary','Distribuidos de granos',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Los Andes','Distribuidos de bebidas',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Monaca','Distribuidos de Harina',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('La Lucha','Distribuidos de allimentos',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Proalca','Distribuidos de alimentos',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Venalcasa','Distribuidos de Leche en polvo',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Proarepa','Distribuidos de harina',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('INN','Distribuidos de Harina, arroz, etc',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Ceval','Distribuidos de alimentos',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Diana','Distribuidos de aceite, mantequilla, etc',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Nestle','Distribuidos de leche, etc',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Saboy','Distribuidos de chocolates',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Pronutrico','Distribuidos de leche, etc',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Lays','Distribuidos de chucherias',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Avelina','Distribuidos de Avena, etc',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Firestone','Distribuidos de cauchos',false);
insert into marca (mar_nombre,mar_descripcion,mar_interna) values ('Goodyear','Distribuidos de cauchos',false);