insert into permiso (per_nombre,per_descripcion) values ('Agregar Almacen','Agregar Almacen');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Beneficio','Agregar Beneficio');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Check','Agregar Check');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Compra','Agregar Compra');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Correo','Agregar Correo');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Despacho','Agregar Despacho');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Ejemplar','Agregar Ejemplar');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Empleado','Agregar Empleado');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Horario','Agregar Horario');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Juridico','Agregar Juridico');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Marca','Agregar Marca');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Natural','Agregar Natural');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Oferta','Agregar Oferta');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Pago','Agregar Pago');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Pasillo','Agregar Pasillo');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Permiso','Agregar Permiso');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Persona Contacto','Agregar Persona Contacto');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Presupuesto','Agregar Presupuesto');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Producto','Agregar Producto');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Proveedor','Agregar Proveedor');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Rol','Agregar Rol');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Rubro','Agregar Rubro');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Telefono','Agregar Telefono');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Tienda','Agregar Tienda');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Tipo de Pago','Agregar Tipo de Pago');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Usuario','Agregar Usuario');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Vacaciones','Agregar Vacaciones');
insert into permiso (per_nombre,per_descripcion) values ('Agregar Zona','Agregar Zona');

insert into permiso (per_nombre,per_descripcion) values ('Eliminar Almacen','Eliminar Almacen');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Beneficio','Eliminar Beneficio');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Check','Eliminar Check');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Compra','Eliminar Compra');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Correo','Eliminar Correo');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Despacho','Eliminar Despacho');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Ejemplar','Eliminar Ejemplar');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Empleado','Eliminar Empleado');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Horario','Eliminar Horario');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Juridico','Eliminar Juridico');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Marca','Eliminar Marca');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Natural','Eliminar Natural');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Oferta','Eliminar Oferta');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Pago','Eliminar Pago');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Pasillo','Eliminar Pasillo');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Permiso','Eliminar Permiso');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Persona Contacto','Eliminar Persona Contacto');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Presupuesto','Eliminar Presupuesto');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Producto','Eliminar Producto');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Proveedor','Eliminar Proveedor');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Rol','Eliminar Rol');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Rubro','Eliminar Rubro');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Telefono','Eliminar Telefono');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Tienda','Eliminar Tienda');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Tipo de Pago','Eliminar Tipo de Pago');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Usuario','Eliminar Usuario');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Vacaciones','Eliminar Vacaciones');
insert into permiso (per_nombre,per_descripcion) values ('Eliminar Zona','Eliminar Zona');

insert into permiso (per_nombre,per_descripcion) values ('Actualizar Almacen','Actualizar Almacen');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Beneficio','Actualizar Beneficio');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Check','Actualizar Check');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Compra','Actualizar Compra');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Correo','Actualizar Correo');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Despacho','Actualizar Despacho');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Ejemplar','Actualizar Ejemplar');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Empleado','Actualizar Empleado');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Horario','Actualizar Horario');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Juridico','Actualizar Juridico');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Marca','Actualizar Marca');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Natural','Actualizar Natural');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Oferta','Actualizar Oferta');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Pago','Actualizar Pago');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Pasillo','Actualizar Pasillo');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Permiso','Actualizar Permiso');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Persona Contacto','Actualizar Persona Contacto');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Presupuesto','Actualizar Presupuesto');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Producto','Actualizar Producto');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Proveedor','Actualizar Proveedor');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Rol','Actualizar Rol');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Rubro','Actualizar Rubro');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Telefono','Actualizar Telefono');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Tienda','Actualizar Tienda');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Tipo de Pago','Actualizar Tipo de Pago');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Usuario','Actualizar Usuario');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Vacaciones','Actualizar Vacaciones');
insert into permiso (per_nombre,per_descripcion) values ('Actualizar Zona','Actualizar Zona');

insert into permiso (per_nombre,per_descripcion) values ('Consultar Almacen','Consultar Almacen');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Beneficio','Consultar Beneficio');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Check','Consultar Check');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Compra','Consultar Compra');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Correo','Consultar Correo');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Despacho','Consultar Despacho');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Ejemplar','Consultar Ejemplar');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Empleado','Consultar Empleado');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Horario','Consultar Horario');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Juridico','Consultar Juridico');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Marca','Consultar Marca');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Natural','Consultar Natural');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Oferta','Consultar Oferta');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Pago','Consultar Pago');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Pasillo','Consultar Pasillo');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Permiso','Consultar Permiso');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Persona Contacto','Consultar Persona Contacto');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Presupuesto','Consultar Presupuesto');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Producto','Consultar Producto');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Proveedor','Consultar Proveedor');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Rol','Consultar Rol');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Rubro','Consultar Rubro');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Telefono','Consultar Telefono');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Tienda','Consultar Tienda');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Tipo de Pago','Consultar Tipo de Pago');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Usuario','Consultar Usuario');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Vacaciones','Consultar Vacaciones');
insert into permiso (per_nombre,per_descripcion) values ('Consultar Zona','Consultar Zona');