insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,2);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',1,2);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',1,2);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,5);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',4,5);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',4,5);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,4);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',7,4);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',7,4);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',10,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',11,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',11,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',14,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',14,6);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',4,5);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',17,5);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',17,5);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',4,5);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,7);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',21,7);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',21,7);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,10);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',24,10);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',24,10);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,9);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',27,9);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',27,9);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',30,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',31,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',31,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',34,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',34,11);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',24,10);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',37,10);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',37,10);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',24,10);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,12);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',41,12);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',41,12);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,15);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',44,15);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',44,15);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,14);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',47,14);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',47,14);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',50,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',51,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',51,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',54,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',54,16);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',44,15);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',57,15);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',57,15);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',44,15);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,17);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',61,17);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',61,17);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,20);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',64,20);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',64,20);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,19);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',67,19);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',67,19);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',70,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',71,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',71,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',74,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',74,21);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',64,20);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',67,20);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',67,20);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',64,20);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,22);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',81,22);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',81,22);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,25);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',84,25);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',84,25);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,24);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',87,24);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',87,24);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',90,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',91,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',91,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',94,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',94,26);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',84,25);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',97,25);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',97,25);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',84,25);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,27);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',101,27);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',101,27);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,30);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',104,30);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',104,30);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,29);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',107,29);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',107,29);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',110,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',111,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',111,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',114,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',114,31);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',104,30);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',117,30);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',117,30);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',104,30);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,32);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',121,32);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',121,32);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,35);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',124,35);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',124,35);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,34);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',127,34);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',127,34);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',130,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',131,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',131,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',134,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',134,36);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',124,35);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',137,35);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',137,35);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',124,35);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,37);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',141,37);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',141,37);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,40);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',144,40);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',144,40);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,39);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',147,39);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',147,39);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',150,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',151,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',151,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',154,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',154,41);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',144,40);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',157,40);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',157,40);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',144,40);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,42);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',161,42);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',161,42);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,45);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',164,45);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',164,45);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,44);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',167,44);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',167,44);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',170,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',171,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',171,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',174,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',174,46);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',164,45);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',177,45);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',177,45);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',164,45);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,47);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',181,47);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',181,47);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,50);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',184,50);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',184,50);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,49);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',187,49);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',187,49);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',190,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',191,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',191,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',194,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',194,51);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',184,50);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',197,50);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',197,50);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',184,50);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,52);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',201,52);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',201,52);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,55);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',204,55);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',204,55);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,54);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',207,54);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',207,54);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',210,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',211,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',211,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',214,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',214,56);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',204,55);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',217,55);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',217,55);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',204,55);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,57);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',221,57);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',221,57);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,60);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',224,60);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',224,60);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,59);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',227,59);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',227,59);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',230,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',231,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',231,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',234,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',234,61);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',224,60);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',237,60);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',237,60);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',224,60);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,62);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',241,62);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',241,62);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,65);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',244,65);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',244,65);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,64);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',247,64);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',247,64);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',250,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',251,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',251,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',254,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',254,66);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',244,65);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',257,65);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',257,65);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',244,65);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,67);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',261,67);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',261,67);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,70);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',264,70);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',264,70);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,69);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',267,69);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',267,69);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',270,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',271,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',271,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',274,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',274,71);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',264,70);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',277,70);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',277,70);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',264,70);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,72);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',281,72);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',281,72);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,75);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',284,75);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',284,75);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,74);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',287,74);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',287,74);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',290,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',291,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',291,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',294,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',294,76);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',284,75);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',297,75);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',297,75);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',284,75);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,77);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',301,77);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',301,77);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,80);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',304,80);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',304,80);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,79);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',307,79);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',307,79);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',310,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',311,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',311,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',314,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',314,81);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',304,80);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',317,80);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',317,80);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',304,80);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,82);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',321,82);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',321,82);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,85);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',324,85);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',324,85);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,84);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',327,84);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',327,84);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',330,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',331,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',331,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',334,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',334,86);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',324,85);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',337,85);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',337,85);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',324,85);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,87);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',341,87);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',341,87);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,90);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',344,90);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',344,90);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,89);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',347,89);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',347,89);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',350,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',351,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',351,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',354,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',354,91);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',344,90);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',357,90);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',357,90);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',344,90);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,92);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',361,92);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',361,92);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,95);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',364,95);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',364,95);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,94);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',367,94);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',367,94);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',370,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',371,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',371,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',374,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',374,96);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',364,95);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',377,95);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',377,95);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',364,95);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,97);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',381,97);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',381,97);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,100);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',384,100);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',384,100);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,99);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',387,99);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',387,99);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',390,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',391,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',391,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',394,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',394,101);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',384,100);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',397,100);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',397,100);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',394,100);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,102);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',401,102);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',401,102);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,105);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',404,105);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',404,105);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,104);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',407,104);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',407,104);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',410,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',411,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',411,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',414,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',414,106);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',404,105);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',417,105);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',417,105);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',404,105);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,107);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',421,107);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',421,107);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,110);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',424,110);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',424,110);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,109);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',427,109);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',427,109);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',430,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',431,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',431,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',434,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',434,111);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',424,110);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',437,110);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',437,110);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',424,110);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,112);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',441,112);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',441,112);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,115);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',444,115);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',444,115);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,114);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',447,114);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',447,114);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',450,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',451,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',451,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',454,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',454,116);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',444,115);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',457,115);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',457,115);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',444,115);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,117);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',461,117);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',461,117);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,120);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',464,120);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',464,120);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,119);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',467,119);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',467,119);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',470,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',471,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',471,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',474,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',474,121);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',464,120);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',477,120);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',477,120);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',464,120);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,122);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',481,122);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',481,122);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,125);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',484,125);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',484,125);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,124);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',487,124);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',487,124);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',490,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',491,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',491,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',494,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',494,126);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',484,125);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',497,125);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',497,125);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',484,125);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,127);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',501,127);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',501,127);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,130);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',504,130);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',504,130);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,129);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',507,129);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',507,129);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',510,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',511,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',511,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',514,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',514,131);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',504,130);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',517,130);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',517,130);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',54,130);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,132);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',521,132);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',521,132);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,135);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',524,135);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',524,135);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,134);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',527,134);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',527,134);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',530,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',531,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',531,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',534,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',534,136);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',524,135);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',537,135);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',537,135);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',524,135);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,137);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',541,137);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',541,137);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,140);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',544,140);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',544,140);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,139);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',547,139);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',547,139);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',550,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',551,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',551,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',554,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',554,141);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',544,140);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',557,140);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',557,140);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',544,140);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,142);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',561,142);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',561,142);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,145);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',564,145);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',564,145);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,144);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',567,144);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',567,144);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',570,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',571,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',571,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',574,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',574,146);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',564,145);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',577,145);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',577,145);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',564,145);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,147);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',581,147);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',581,147);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,150);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',584,150);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',584,150);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,149);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',587,149);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',587,149);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',590,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',591,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',591,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',594,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',594,151);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',584,150);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',597,150);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',597,150);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',584,150);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,152);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',601,152);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',601,152);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,155);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',604,155);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',604,155);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,154);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',607,154);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',607,154);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',610,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',611,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',611,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',614,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',614,156);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',604,155);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',617,155);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',617,155);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',604,155);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,157);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',621,157);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',621,157);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,160);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',624,160);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',624,160);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,159);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',627,159);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',627,159);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',630,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',631,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',631,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',634,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',634,161);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',624,160);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',637,160);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',637,160);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',624,160);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,162);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',641,162);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',641,162);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,165);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',644,165);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',644,165);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,164);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',647,164);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',647,164);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',650,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',651,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',651,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',654,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',654,166);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',644,165);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',657,165);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',657,165);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',644,165);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,167);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',661,167);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',661,167);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,170);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',664,170);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',664,170);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,169);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',667,169);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',667,169);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',670,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',671,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',671,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',674,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',674,171);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',664,170);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',677,170);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',677,170);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',664,170);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,172);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',681,172);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',681,172);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,175);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',684,175);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',684,175);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,174);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',687,174);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',687,174);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',690,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',691,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',691,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',694,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',694,176);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',684,175);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',697,175);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',697,175);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',684,175);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,177);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',701,177);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',701,177);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,180);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',704,180);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',704,180);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,179);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',707,179);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',707,179);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',710,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',711,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',711,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',714,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',714,181);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',704,180);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',717,180);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',717,180);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',704,180);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,182);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',721,182);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',721,182);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,185);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',724,185);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',724,185);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,184);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',727,184);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',727,184);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',730,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',731,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',731,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',734,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',734,186);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',724,185);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',737,185);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',737,185);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',724,185);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,187);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',741,187);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',741,187);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,190);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',744,190);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',744,190);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,189);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',747,189);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',747,189);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',750,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',751,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',751,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',754,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',754,191);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',744,190);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',757,190);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',757,190);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',744,190);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,192);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',761,192);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',761,192);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,195);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',764,195);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',764,195);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,194);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',767,194);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',767,194);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',770,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',771,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',771,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',774,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',774,196);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',764,195);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',777,195);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',777,195);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',764,195);

insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Textiles','Telas, Ropa , etc',null,197);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ropa','Camisas, Franelas, etc',781,197);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Zapatos','Zapatos de Caballero, zandalias, etc',781,197);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Alimentos','Harina de Trico, arroz, caraotas, etc',null,200);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Granos','Caraotas, lentejas, arroz, etc',784,200);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Azucar y Sal','Azucar Y Sal',784,200);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Automotriz','Cauchos, aceites, etc',null,199);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cauchos','Cauchos',787,199);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Rines','Rines',787,199);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Bebidas','Licores, refrescos, etc',null,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Licores','Ron, Vodka, Tequila, etc',790,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Ron','Ron',791,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Vodka','Vodka',791,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Refrescos','Pepsicola, cocacola, etc',null,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pepsicola','Pepsicola',794,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Cocacola','Cocacola',794,201);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carniceria','Carnes, pollos, etc',784,200);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Carnes rojas','Carnes rojas',797,200);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pollo','Pollos',797,200);
insert into rubro (rub_nombre, rub_descripcion,rub_fk_rubro,rub_fk_almacen) values ('Pan','Panes',784,200);