insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',1);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',2);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',3);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',4);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',5);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',6);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',7);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',8);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',9);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',10);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',11);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',12);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',13);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',14);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',15);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',16);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',17);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',18);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',19);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',20);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',21);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',22);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',23);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',24);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',25);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',26);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',27);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',28);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',29);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',30);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',31);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',32);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',33);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',34);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',35);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',36);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',37);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',38);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',39);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Talento Humano','Manejo todo lo referente al personal',40);

insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',1);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',2);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',3);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',4);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',5);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',6);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',7);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',8);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',9);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',10);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',11);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',12);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',13);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',14);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',15);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',16);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',17);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',18);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',19);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',20);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',21);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',22);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',23);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',24);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',25);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',26);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',27);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',28);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',29);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',30);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',31);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',32);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',33);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',34);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',35);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',36);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',37);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',38);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',39);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Compras','Manejo lo referente a la reposicion de inventario',40);

insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',1);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',2);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',3);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',4);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',5);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',6);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',7);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',8);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',9);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',10);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',11);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',12);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',13);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',14);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',15);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',16);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',17);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',18);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',19);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',20);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',21);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',22);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',23);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',24);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',25);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',26);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',27);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',28);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',29);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',30);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',31);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',32);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',33);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',34);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',35);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',36);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',37);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',38);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',39);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Ventas','Manejo lo referente a la venta de productos, presupuestos, etc...',40);

insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',1);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',2);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',3);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',4);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',5);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',6);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',7);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',8);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',9);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',10);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',11);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',12);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',13);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',14);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',15);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',16);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',17);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',18);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',19);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',20);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',21);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',22);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',23);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',24);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',25);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',26);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',27);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',28);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',29);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',30);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',31);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',32);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',33);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',34);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',35);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',36);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',37);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',38);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',39);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Inventario','Manejo lo referente al inventario',40);

insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',1);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',2);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',3);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',4);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',5);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',6);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',7);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',8);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',9);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',10);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',11);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',12);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',13);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',14);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',15);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',16);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',17);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',18);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',19);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',20);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',21);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',22);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',23);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',24);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',25);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',26);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',27);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',28);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',29);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',30);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',31);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',32);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',33);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',34);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',35);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',36);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',37);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',38);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',39);
insert into departamento (dep_nombre,dep_descripcion,dep_fk_tienda) values ('Tecnologia','Manejo lo referente a la tecnologia',40);