/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class AdministracionDeTiendas extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private int select;
    /**
     * Creates new form AdministracionDeTiendas
     */
    public AdministracionDeTiendas() {
        initComponents();
             getContentPane().setBackground(java.awt.Color.white);
        defaultTableModel.addColumn("Nombre");
        defaultTableModel.addColumn("Fecha");
        defaultTableModel.addColumn("Valor Puntos");
        jTable1.setModel(defaultTableModel);
        jTable1.getColumnModel().getColumn(0).setWidth(150);
        jTable1.getColumnModel().getColumn(1).setWidth(100);
        jTable1.getColumnModel().getColumn(2).setWidth(100);
        select=0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tiendas = new javax.swing.JLabel();
        jTextField_NombreTienda = new javax.swing.JTextField();
        jButton_NuevaTienda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1Eliminar = new javax.swing.JButton();
        jButton1Modificar = new javax.swing.JButton();
        jButton1Consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_tiendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_tiendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tiendas.setText("Tiendas");

        jTextField_NombreTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreTiendaActionPerformed(evt);
            }
        });
        jTextField_NombreTienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NombreTiendaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NombreTiendaKeyTyped(evt);
            }
        });

        jButton_NuevaTienda.setText("Nueva Tienda");
        jButton_NuevaTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NuevaTiendaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1Eliminar.setText("Eliminar");
        jButton1Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EliminarActionPerformed(evt);
            }
        });

        jButton1Modificar.setText("Modificar");
        jButton1Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ModificarActionPerformed(evt);
            }
        });

        jButton1Consultar.setText("Consultar");
        jButton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel_tiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(472, 472, 472)
                            .addComponent(jButton_NuevaTienda)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_NombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel_tiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_NuevaTienda)
                    .addComponent(jTextField_NombreTienda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1Consultar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NombreTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreTiendaActionPerformed

    private void jTextField_NombreTiendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreTiendaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            defaultTableModel = new DefaultTableModel();
            defaultTableModel.addColumn("Nombre");
            defaultTableModel.addColumn("Fecha");
            defaultTableModel.addColumn("Valor Puntos");
            jTable1.setModel(defaultTableModel);
            jTable1.getColumnModel().getColumn(0).setWidth(150);
            jTable1.getColumnModel().getColumn(1).setWidth(100);
            jTable1.getColumnModel().getColumn(2).setWidth(100);
            try{
                ArrayList<String> tiendas = Controlador.ControladorTienda.BuscarTiendas(jTextField_NombreTienda.getText());
                int i=0;
                while (i<tiendas.size())
                {
                    defaultTableModel.addRow(new Object[] {tiendas.get(i+1),tiendas.get(i+2),tiendas.get(i+3)});
                    i=i+5;
                }
                
            }
            catch(Exception e)
            {
                
            }
            
            
            
            
        }
    }//GEN-LAST:event_jTextField_NombreTiendaKeyReleased

    private void jTextField_NombreTiendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreTiendaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_NombreTiendaKeyTyped

    private void jButton1EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EliminarActionPerformed
        // TODO add your handling code here:
        try{
            if(jTable1.getSelectedRow()>=0 && jTable1.getSelectedRow()<=9)
            {
                
                if(Controlador.ControladorTienda.EliminarTienda((String) defaultTableModel.getValueAt(select, 0)))
                {
                    JOptionPane.showMessageDialog(rootPane, "Tienda Eliminada", "Tienda", JOptionPane.INFORMATION_MESSAGE);
                    defaultTableModel.removeRow(select);
                    jTable1.setModel(defaultTableModel);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Error al Eliminar", "Tienda", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jButton1EliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        select = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_NuevaTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NuevaTiendaActionPerformed
        // TODO add your handling code here:
        RegistrarTienda registrarTienda = new RegistrarTienda(this);
        registrarTienda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_NuevaTiendaActionPerformed

    private void jButton1ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ModificarActionPerformed
        // TODO add your handling code here:
        try
        {
            ModificarTienda modificarTienda = new ModificarTienda(this,(String) defaultTableModel.getValueAt(select, 0));
            modificarTienda.setVisible(true);
            this.setVisible(false);
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jButton1ModificarActionPerformed

    private void jButton1ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarActionPerformed
        // TODO add your handling code here:
        try{
            ConsutarTienda consutarTienda = new ConsutarTienda(this, (String) defaultTableModel.getValueAt(select, 0));
            consutarTienda.setVisible(true);
            this.setVisible(false);
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jButton1ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeTiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeTiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeTiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeTiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionDeTiendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Consultar;
    private javax.swing.JButton jButton1Eliminar;
    private javax.swing.JButton jButton1Modificar;
    private javax.swing.JButton jButton_NuevaTienda;
    private javax.swing.JLabel jLabel_tiendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_NombreTienda;
    // End of variables declaration//GEN-END:variables
}
