/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;
import Controlador.RegistroClienteController;

/**
 *
 * @author migue
 */
public class RegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jlblRegistroCLienteTitulo = new javax.swing.JLabel();
        jTabbedPaneRegistroCliente = new javax.swing.JTabbedPane();
        jScrollPaneRegistroNAtural = new javax.swing.JScrollPane();
        PanelPersonaNatural = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jbtnRegistroCLienteNatural = new javax.swing.JButton();
        textRegistroCLienteNaturalNombre = new javax.swing.JTextField();
        textRegistroCLienteNaturalSegundoNombre = new javax.swing.JTextField();
        textRegistroCLienteNaturalApellido = new javax.swing.JTextField();
        textRegistroCLienteNaturalTelefono = new javax.swing.JTextField();
        textRegistroCLienteNaturalEmail = new javax.swing.JTextField();
        textRegistroCLienteNaturalSegundoApellido = new javax.swing.JTextField();
        textRegistroCLienteNaturalUser = new javax.swing.JTextField();
        textRegistroCLienteNaturalPass = new javax.swing.JTextField();
        textRegistroCLienteNaturalPreguntaSecreta = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteNaturalEstado = new javax.swing.JComboBox();
        jLabel53 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteNaturalMunicipio = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteNaturalParroquia = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalTelefono = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalCedula = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalEmail = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalPreguntaSecreta = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalRespuestaSecreta = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        textRegistroCLienteNaturalCedula = new javax.swing.JTextField();
        textRegistroCLienteNaturalRespuestaSecreta = new javax.swing.JTextField();
        lblErrorRegistoClienteNaturalPrimerNombre = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalSegundoNOmbre = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalApellido = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalSegundoApellido = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalEmail1 = new javax.swing.JLabel();
        lblErrorRegistoClienteNaturalEmail2 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        textRegistroCLienteNaturalRif = new javax.swing.JTextField();
        lblErrorRegistoClienteNaturalRif = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jScrollPanePersonaJuridica = new javax.swing.JScrollPane();
        PanelPersonaJuridica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtnRegistroCLienteJuridico = new javax.swing.JButton();
        textRegistroCLienteJuridicoDenominacionComercial = new javax.swing.JTextField();
        textRegistroCLienteJuridicoRazonSocial = new javax.swing.JTextField();
        textRegistroCLienteJuridicoRif = new javax.swing.JTextField();
        textRegistroCLienteJuridicoTelefono = new javax.swing.JTextField();
        textRegistroCLienteJuridicoWeb = new javax.swing.JTextField();
        textRegistroCLienteJuridicoEmail = new javax.swing.JTextField();
        textRegistroCLienteJuridicoCapitalDisponible = new javax.swing.JTextField();
        textRegistroCLienteJuridicoUsuario = new javax.swing.JTextField();
        textRegistroCLienteJuridicoPass = new javax.swing.JTextField();
        textRegistroCLienteJuridicoPreguntaSecreta = new javax.swing.JTextField();
        textRegistroCLienteJuridicoRespuestaSecreta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal = new javax.swing.JComboBox();
        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoDenominacionComercial = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoRazonSocial = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoRif = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoTelefono = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoWeb = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoEmail = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoCapitalDisponilbe = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoPreguntaSecreta = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoRespuestaSecreta = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoCapitalDisponilbe2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal = new javax.swing.JComboBox();
        jtbtnRegistroCLienteVolver = new javax.swing.JButton();

        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("(*)");

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("(*)");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("(*) Campos Obligatorios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrarse");

        jlblRegistroCLienteTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblRegistroCLienteTitulo.setText("Registro Cliente");

        PanelPersonaNatural.setToolTipText("");

        jLabel28.setText("Nombre");

        jLabel30.setText("Segundo Nombre");

        jLabel31.setText("Apellido");

        jLabel33.setText("Direccion");

        jLabel34.setText("Telefono");

        jLabel35.setText("Cedula");

        jLabel37.setText("Email");

        jLabel40.setText("Segundo Apellido");

        jLabel45.setText("Usuario");

        jLabel46.setText("Contraseña");

        jLabel47.setText("Pregunta Secreta");

        jLabel48.setText("Respuesta Secreta");

        jbtnRegistroCLienteNatural.setText("Registrar");

        jLabel52.setText("Estado:");

        jLabel53.setText("Municipio:");

        jLabel54.setText("Parroquia:");

        jLabel55.setForeground(new java.awt.Color(255, 0, 0));
        jLabel55.setText("(*)");

        jLabel57.setForeground(new java.awt.Color(255, 0, 0));
        jLabel57.setText("(*)");

        jLabel60.setForeground(new java.awt.Color(255, 0, 0));
        jLabel60.setText("(*) Campos Obligatorios");

        lblErrorRegistoClienteNaturalTelefono.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalTelefono.setText("Error, Telefono incorrecto");

        lblErrorRegistoClienteNaturalCedula.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalCedula.setText("Error, ingresar una cedula correcta");

        lblErrorRegistoClienteNaturalEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalEmail.setText("Error, Email incorrecto");

        jLabel61.setForeground(new java.awt.Color(255, 0, 0));
        jLabel61.setText("(*)");

        lblErrorRegistoClienteNaturalPreguntaSecreta.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalPreguntaSecreta.setText("Error, Igresar caracteres alfanumericos");

        jLabel62.setForeground(new java.awt.Color(255, 0, 0));
        jLabel62.setText("(*)");

        jLabel63.setForeground(new java.awt.Color(255, 0, 0));
        jLabel63.setText("(*)");

        lblErrorRegistoClienteNaturalRespuestaSecreta.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalRespuestaSecreta.setText("Error, Igresar caracteres alfanumericos");

        jLabel64.setForeground(new java.awt.Color(255, 0, 0));
        jLabel64.setText("(*)");

        jLabel65.setForeground(new java.awt.Color(0, 0, 255));
        jLabel65.setText("(2222)222-2222");

        lblErrorRegistoClienteNaturalPrimerNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalPrimerNombre.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteNaturalSegundoNOmbre.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalSegundoNOmbre.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteNaturalApellido.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalApellido.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteNaturalSegundoApellido.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalSegundoApellido.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteNaturalEmail1.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalEmail1.setText("Campo Obligatorio");

        lblErrorRegistoClienteNaturalEmail2.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalEmail2.setText("Campo Obligatorio");

        jLabel49.setText("RIF");

        lblErrorRegistoClienteNaturalRif.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteNaturalRif.setText("Error, ingresar una cedula correcta");

        jLabel58.setForeground(new java.awt.Color(255, 0, 0));
        jLabel58.setText("(*)");

        javax.swing.GroupLayout PanelPersonaNaturalLayout = new javax.swing.GroupLayout(PanelPersonaNatural);
        PanelPersonaNatural.setLayout(PanelPersonaNaturalLayout);
        PanelPersonaNaturalLayout.setHorizontalGroup(
            PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textRegistroCLienteNaturalPreguntaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textRegistroCLienteNaturalRespuestaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                                .addComponent(jLabel63)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblErrorRegistoClienteNaturalRespuestaSecreta))
                                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                                .addComponent(jLabel62)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblErrorRegistoClienteNaturalPreguntaSecreta))))
                                    .addComponent(textRegistroCLienteNaturalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                        .addComponent(textRegistroCLienteNaturalPass, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel64)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorRegistoClienteNaturalEmail2))
                                    .addComponent(jbtnRegistroCLienteNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel60))))
                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel49))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textRegistroCLienteNaturalNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                            .addComponent(textRegistroCLienteNaturalSegundoNombre)
                                            .addComponent(textRegistroCLienteNaturalApellido)
                                            .addComponent(textRegistroCLienteNaturalTelefono)
                                            .addComponent(textRegistroCLienteNaturalSegundoApellido)
                                            .addComponent(textRegistroCLienteNaturalCedula, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textRegistroCLienteNaturalRif))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                                .addComponent(jLabel65)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblErrorRegistoClienteNaturalTelefono))
                                            .addComponent(lblErrorRegistoClienteNaturalPrimerNombre)
                                            .addComponent(lblErrorRegistoClienteNaturalSegundoNOmbre)
                                            .addComponent(lblErrorRegistoClienteNaturalApellido)
                                            .addComponent(lblErrorRegistoClienteNaturalSegundoApellido)
                                            .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                                    .addComponent(jLabel58)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblErrorRegistoClienteNaturalRif))
                                                .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                                    .addComponent(jLabel57)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblErrorRegistoClienteNaturalCedula)))))
                                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxRegistroCLienteNaturalEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel53)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxRegistroCLienteNaturalMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxRegistroCLienteNaturalParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textRegistroCLienteNaturalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                        .addComponent(jLabel61)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorRegistoClienteNaturalEmail1))
                                    .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorRegistoClienteNaturalEmail)))))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelPersonaNaturalLayout.setVerticalGroup(
            PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaNaturalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textRegistroCLienteNaturalNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalPrimerNombre))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(textRegistroCLienteNaturalSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalSegundoNOmbre))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(textRegistroCLienteNaturalApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalApellido))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(textRegistroCLienteNaturalSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalSegundoApellido))
                .addGap(23, 23, 23)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel52)
                    .addComponent(jComboBoxRegistroCLienteNaturalEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54)
                    .addComponent(jComboBoxRegistroCLienteNaturalParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegistroCLienteNaturalMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(textRegistroCLienteNaturalTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalTelefono)
                    .addComponent(jLabel65))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel57)
                    .addComponent(lblErrorRegistoClienteNaturalCedula)
                    .addComponent(textRegistroCLienteNaturalCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(textRegistroCLienteNaturalRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalRif)
                    .addComponent(jLabel58))
                .addGap(10, 10, 10)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRegistroCLienteNaturalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel55)
                    .addComponent(lblErrorRegistoClienteNaturalEmail))
                .addGap(13, 13, 13)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(textRegistroCLienteNaturalUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteNaturalEmail1)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRegistroCLienteNaturalPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel64)
                    .addComponent(lblErrorRegistoClienteNaturalEmail2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRegistroCLienteNaturalPreguntaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel62)
                    .addComponent(lblErrorRegistoClienteNaturalPreguntaSecreta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addGroup(PanelPersonaNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textRegistroCLienteNaturalRespuestaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel63)
                        .addComponent(lblErrorRegistoClienteNaturalRespuestaSecreta)))
                .addGap(18, 18, 18)
                .addComponent(jLabel60)
                .addGap(1, 1, 1)
                .addComponent(jbtnRegistroCLienteNatural)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jScrollPaneRegistroNAtural.setViewportView(PanelPersonaNatural);

        jTabbedPaneRegistroCliente.addTab("Persona Natural", jScrollPaneRegistroNAtural);

        PanelPersonaJuridica.setToolTipText("");

        jLabel1.setText("Denominadion Comercial");

        jLabel2.setText("Razon Social");

        jLabel3.setText("RIF");

        jLabel4.setText("Direccion Fisica");

        jLabel5.setText("Direccion Fiscal");

        jLabel6.setText("Telefono");

        jLabel7.setText("Pagina Web");

        jLabel8.setText("Email");

        jLabel9.setText("Capital Disponible");

        jLabel10.setText("Usuario");

        jLabel11.setText("Contraseña");

        jLabel12.setText("Pregunta Secreta");

        jLabel13.setText("Respuesta Secreta");

        jbtnRegistroCLienteJuridico.setText("Registrar");

        jLabel14.setText("Estado:");

        jLabel15.setText("Municipio:");

        jLabel16.setText("Parroquia:");

        jLabel18.setText("Municipio:");

        jLabel19.setText("Parroquia:");

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("(*)");

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("(*)");

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("(*)");

        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("(*)");

        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("(*)");

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("(*) Campos Obligatorios");

        lblErrorRegistoClienteJuridicoDenominacionComercial.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoDenominacionComercial.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteJuridicoRazonSocial.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoRazonSocial.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteJuridicoRif.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoRif.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteJuridicoTelefono.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoTelefono.setText("Error, Telefono incorrecto");

        lblErrorRegistoClienteJuridicoWeb.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoWeb.setText("Error, dirccion web incorrecta");

        lblErrorRegistoClienteJuridicoEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoEmail.setText("Error, Email incorrecto");

        lblErrorRegistoClienteJuridicoCapitalDisponilbe.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoCapitalDisponilbe.setText("Ingresar cifra correcta");

        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("(*)");

        lblErrorRegistoClienteJuridicoPreguntaSecreta.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoPreguntaSecreta.setText("Error, Igresar caracteres alfanumericos");

        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("(*)");

        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("(*)");

        lblErrorRegistoClienteJuridicoRespuestaSecreta.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoRespuestaSecreta.setText("Error, Igresar caracteres alfanumericos");

        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("(*)");

        jLabel42.setForeground(new java.awt.Color(0, 0, 255));
        jLabel42.setText("(2222)222-2222");

        jLabel43.setForeground(new java.awt.Color(0, 0, 255));
        jLabel43.setText("www.xyz.zxy.xy");

        jLabel44.setForeground(new java.awt.Color(255, 0, 0));
        jLabel44.setText("(*)");

        lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido.setText("Usuario Repetido");

        lblErrorRegistoClienteJuridicoCapitalDisponilbe2.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoCapitalDisponilbe2.setText("Campo Obligatorio");

        jLabel32.setText("Estado:");

        javax.swing.GroupLayout PanelPersonaJuridicaLayout = new javax.swing.GroupLayout(PanelPersonaJuridica);
        PanelPersonaJuridica.setLayout(PanelPersonaJuridicaLayout);
        PanelPersonaJuridicaLayout.setHorizontalGroup(
            PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel32))
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15))
                                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel18)))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica, 0, 161, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorRegistoClienteJuridicoWeb)
                                    .addComponent(lblErrorRegistoClienteJuridicoTelefono))
                                .addGap(0, 191, Short.MAX_VALUE))))
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textRegistroCLienteJuridicoDenominacionComercial)
                            .addComponent(textRegistroCLienteJuridicoRazonSocial)
                            .addComponent(textRegistroCLienteJuridicoRif)
                            .addComponent(textRegistroCLienteJuridicoTelefono)
                            .addComponent(textRegistroCLienteJuridicoWeb)
                            .addComponent(textRegistroCLienteJuridicoEmail)
                            .addComponent(textRegistroCLienteJuridicoCapitalDisponible)
                            .addComponent(textRegistroCLienteJuridicoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(textRegistroCLienteJuridicoPass)
                            .addComponent(textRegistroCLienteJuridicoPreguntaSecreta)
                            .addComponent(textRegistroCLienteJuridicoRespuestaSecreta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorRegistoClienteJuridicoRazonSocial))
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblErrorRegistoClienteJuridicoDenominacionComercial))
                            .addComponent(jLabel36)
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorRegistoClienteJuridicoRespuestaSecreta))
                            .addComponent(jLabel41)
                            .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPersonaJuridicaLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblErrorRegistoClienteJuridicoPreguntaSecreta))
                                .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                    .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel44))
                                    .addGap(34, 34, 34)
                                    .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblErrorRegistoClienteJuridicoCapitalDisponilbe)
                                        .addComponent(lblErrorRegistoClienteJuridicoEmail)
                                        .addComponent(lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido)
                                        .addComponent(lblErrorRegistoClienteJuridicoCapitalDisponilbe2))))
                            .addComponent(jLabel42)
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43))
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorRegistoClienteJuridicoRif)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addComponent(jbtnRegistroCLienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        PanelPersonaJuridicaLayout.setVerticalGroup(
            PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textRegistroCLienteJuridicoDenominacionComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(lblErrorRegistoClienteJuridicoDenominacionComercial))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textRegistroCLienteJuridicoRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(lblErrorRegistoClienteJuridicoRazonSocial))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textRegistroCLienteJuridicoRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(lblErrorRegistoClienteJuridicoRif))
                .addGap(20, 20, 20)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textRegistroCLienteJuridicoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteJuridicoTelefono)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textRegistroCLienteJuridicoWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(lblErrorRegistoClienteJuridicoWeb)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textRegistroCLienteJuridicoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(lblErrorRegistoClienteJuridicoEmail))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textRegistroCLienteJuridicoCapitalDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteJuridicoCapitalDisponilbe)
                    .addComponent(jLabel44))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textRegistroCLienteJuridicoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textRegistroCLienteJuridicoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(lblErrorRegistoClienteJuridicoCapitalDisponilbe2))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblErrorRegistoClienteJuridicoPreguntaSecreta)
                            .addComponent(jLabel38))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textRegistroCLienteJuridicoPreguntaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)))
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(lblErrorRegistoClienteJuridicoRespuestaSecreta)
                    .addComponent(textRegistroCLienteJuridicoRespuestaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegistroCLienteJuridico)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jScrollPanePersonaJuridica.setViewportView(PanelPersonaJuridica);

        jTabbedPaneRegistroCliente.addTab("Persona Juridica", jScrollPanePersonaJuridica);

        jtbtnRegistroCLienteVolver.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneRegistroCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblRegistroCLienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbtnRegistroCLienteVolver))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblRegistroCLienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbtnRegistroCLienteVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneRegistroCliente.getAccessibleContext().setAccessibleName("CLiente");
        jTabbedPaneRegistroCliente.getAccessibleContext().setAccessibleDescription("Valido para clientes ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setRegistroClienteController(RegistroClienteController c){
          //Botones  
            jtbtnRegistroCLienteVolver.addActionListener(c);
            jbtnRegistroCLienteNatural.addActionListener(c);
            jbtnRegistroCLienteJuridico.addActionListener(c);
            
            //Text Field
                       //Juridico
                     textRegistroCLienteJuridicoCapitalDisponible.addActionListener(c);
                     textRegistroCLienteJuridicoDenominacionComercial.addActionListener(c);
                     textRegistroCLienteJuridicoEmail.addActionListener(c);
                     textRegistroCLienteJuridicoPass.addActionListener(c);
                     textRegistroCLienteJuridicoPreguntaSecreta.addActionListener(c);
                     textRegistroCLienteJuridicoRazonSocial.addActionListener(c);
                     textRegistroCLienteJuridicoRespuestaSecreta.addActionListener(c);
                     textRegistroCLienteJuridicoRif.addActionListener(c);
                     textRegistroCLienteJuridicoTelefono.addActionListener(c);
                     textRegistroCLienteJuridicoUsuario.addActionListener(c);
                     textRegistroCLienteJuridicoWeb.addActionListener(c);
                     
                     //Natural
                     textRegistroCLienteNaturalApellido.addActionListener(c);
                     textRegistroCLienteNaturalCedula.addActionListener(c);
                     
                     textRegistroCLienteNaturalEmail.addActionListener(c);
                     textRegistroCLienteNaturalNombre.addActionListener(c);
                     textRegistroCLienteNaturalPass.addActionListener(c);
                     textRegistroCLienteNaturalPreguntaSecreta.addActionListener(c);
                     textRegistroCLienteNaturalRespuestaSecreta.addActionListener(c);
                     textRegistroCLienteNaturalRif.addActionListener(c);
                     textRegistroCLienteNaturalSegundoApellido.addActionListener(c);
                     textRegistroCLienteNaturalSegundoNombre.addActionListener(c);
                     textRegistroCLienteNaturalTelefono.addActionListener(c);
                     textRegistroCLienteNaturalUser.addActionListener(c);
                     
                     //Combobox
                         jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal.addActionListener(c);
                        jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica.addActionListener(c);
                        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal.addActionListener(c);
                        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica.addActionListener(c);
                         jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal.addActionListener(c);
                          jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica.addActionListener(c);
                        
                          jComboBoxRegistroCLienteNaturalEstado.addActionListener(c);
                          jComboBoxRegistroCLienteNaturalMunicipio.addActionListener(c);
                          jComboBoxRegistroCLienteNaturalParroquia.addActionListener(c);
                     
            
        
    }
    public void MustraRegisroCliente (){
               lblErrorRegistoClienteJuridicoCapitalDisponilbe.setVisible(false);
               lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido.setVisible(false);
               lblErrorRegistoClienteJuridicoCapitalDisponilbe2.setVisible(false);
               lblErrorRegistoClienteJuridicoDenominacionComercial.setVisible(false);
                lblErrorRegistoClienteJuridicoEmail.setVisible(false);
                lblErrorRegistoClienteJuridicoPreguntaSecreta.setVisible(false);
                lblErrorRegistoClienteJuridicoRazonSocial.setVisible(false);
               lblErrorRegistoClienteJuridicoRespuestaSecreta.setVisible(false);
               lblErrorRegistoClienteJuridicoRif.setVisible(false);
               lblErrorRegistoClienteJuridicoTelefono.setVisible(false);
               lblErrorRegistoClienteJuridicoWeb.setVisible(false);
               lblErrorRegistoClienteNaturalApellido.setVisible(false);
               lblErrorRegistoClienteNaturalCedula.setVisible(false);
               lblErrorRegistoClienteNaturalEmail.setVisible(false);
               lblErrorRegistoClienteNaturalPreguntaSecreta.setVisible(false);
               lblErrorRegistoClienteNaturalPrimerNombre.setVisible(false);
                lblErrorRegistoClienteNaturalRespuestaSecreta.setVisible(false);
                lblErrorRegistoClienteNaturalRif.setVisible(false);
                lblErrorRegistoClienteNaturalSegundoApellido.setVisible(false);
               lblErrorRegistoClienteNaturalSegundoNOmbre.setVisible(false);
                lblErrorRegistoClienteNaturalTelefono.setVisible(false);
                lblErrorRegistoClienteNaturalEmail1.setVisible(false);
                lblErrorRegistoClienteNaturalEmail2.setVisible(false);
             //   lblErrorRegistoClienteNaturalEmail3.setVisible(false);
                
           
                
                setTitle("Bienvenido");
		//setResizable(false);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLocationRelativeTo(null);
		setVisible(true);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelPersonaJuridica;
    public javax.swing.JPanel PanelPersonaNatural;
    public javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal;
    public javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica;
    public javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal;
    public javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica;
    public javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal;
    public javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica;
    public javax.swing.JComboBox jComboBoxRegistroCLienteNaturalEstado;
    public javax.swing.JComboBox jComboBoxRegistroCLienteNaturalMunicipio;
    public javax.swing.JComboBox jComboBoxRegistroCLienteNaturalParroquia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPanePersonaJuridica;
    public javax.swing.JScrollPane jScrollPaneRegistroNAtural;
    private javax.swing.JTabbedPane jTabbedPaneRegistroCliente;
    public javax.swing.JButton jbtnRegistroCLienteJuridico;
    public javax.swing.JButton jbtnRegistroCLienteNatural;
    private javax.swing.JLabel jlblRegistroCLienteTitulo;
    public javax.swing.JButton jtbtnRegistroCLienteVolver;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoCapitalDisponilbe;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoCapitalDisponilbe2;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoCapitalUsuarioRepetido;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoDenominacionComercial;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoEmail;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoPreguntaSecreta;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoRazonSocial;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoRespuestaSecreta;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoRif;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoTelefono;
    public javax.swing.JLabel lblErrorRegistoClienteJuridicoWeb;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalApellido;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalCedula;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalEmail;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalEmail1;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalEmail2;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalPreguntaSecreta;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalPrimerNombre;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalRespuestaSecreta;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalRif;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalSegundoApellido;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalSegundoNOmbre;
    public javax.swing.JLabel lblErrorRegistoClienteNaturalTelefono;
    public javax.swing.JTextField textRegistroCLienteJuridicoCapitalDisponible;
    public javax.swing.JTextField textRegistroCLienteJuridicoDenominacionComercial;
    public javax.swing.JTextField textRegistroCLienteJuridicoEmail;
    public javax.swing.JTextField textRegistroCLienteJuridicoPass;
    public javax.swing.JTextField textRegistroCLienteJuridicoPreguntaSecreta;
    public javax.swing.JTextField textRegistroCLienteJuridicoRazonSocial;
    public javax.swing.JTextField textRegistroCLienteJuridicoRespuestaSecreta;
    public javax.swing.JTextField textRegistroCLienteJuridicoRif;
    public javax.swing.JTextField textRegistroCLienteJuridicoTelefono;
    public javax.swing.JTextField textRegistroCLienteJuridicoUsuario;
    public javax.swing.JTextField textRegistroCLienteJuridicoWeb;
    public javax.swing.JTextField textRegistroCLienteNaturalApellido;
    public javax.swing.JTextField textRegistroCLienteNaturalCedula;
    public javax.swing.JTextField textRegistroCLienteNaturalEmail;
    public javax.swing.JTextField textRegistroCLienteNaturalNombre;
    public javax.swing.JTextField textRegistroCLienteNaturalPass;
    public javax.swing.JTextField textRegistroCLienteNaturalPreguntaSecreta;
    public javax.swing.JTextField textRegistroCLienteNaturalRespuestaSecreta;
    public javax.swing.JTextField textRegistroCLienteNaturalRif;
    public javax.swing.JTextField textRegistroCLienteNaturalSegundoApellido;
    public javax.swing.JTextField textRegistroCLienteNaturalSegundoNombre;
    public javax.swing.JTextField textRegistroCLienteNaturalTelefono;
    public javax.swing.JTextField textRegistroCLienteNaturalUser;
    // End of variables declaration//GEN-END:variables
}
