/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;
import Controlador.ControladorProveedor;
import Controlador.RegistroClienteController;

/**
 *
 * @author migue
 */
public class RegistroProveedor extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCliente
     */
    public RegistroProveedor() {
        initComponents();
    }

        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProveedor().setVisible(true);
               // Controlador.ControladorProveedor.RegistrarProveedor("1", "hola", "chao", "www", 6, 5, 8);
            
              // Controlador.ControladorProveedor.EliminarProveedor("1");
              // Controlador.ControladorProveedor.RegistrarProveedor("1", "hi", "jhgg", "sdffsdf", 4, 9, 8);
               //Controlador.ControladorProveedor.ActualizarProveedor("1", "hola", "jksdgfhdgf", "sdfsdf", 3, 8, 10);
               ControladorProveedor.BuscarProveedor("1");
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jlblRegistroCLienteTitulo = new javax.swing.JLabel();
        jTabbedPaneRegistroCliente = new javax.swing.JTabbedPane();
        jScrollPanePersonaJuridica = new javax.swing.JScrollPane();
        PanelPersonaJuridica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnRegistroCLienteJuridico = new javax.swing.JButton();
        textRegistroCLienteJuridicoDenominacionComercial = new javax.swing.JTextField();
        textRegistroCLienteJuridicoRazonSocial = new javax.swing.JTextField();
        textRegistroCLienteJuridicoRif = new javax.swing.JTextField();
        textRegistroCLienteJuridicoTelefono = new javax.swing.JTextField();
        textRegistroCLienteJuridicoUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal = new javax.swing.JComboBox();
        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoDenominacionComercial = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoRazonSocial = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoRif = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoTelefono = new javax.swing.JLabel();
        lblErrorRegistoClienteJuridicoWeb = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jbtnRegistroCLienteJuridico1 = new javax.swing.JButton();
        jbtnRegistroCLienteJuridico2 = new javax.swing.JButton();
        jtbtnRegistroCLienteVolver = new javax.swing.JButton();

        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("(*)");

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("(*)");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("(*) Campos Obligatorios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrarse");

        jlblRegistroCLienteTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblRegistroCLienteTitulo.setText("Registro Proveedor");

        PanelPersonaJuridica.setToolTipText("");

        jLabel1.setText("Denominadion Comercial");

        jLabel2.setText("Razon Social");

        jLabel3.setText("RIF");

        jLabel4.setText("Direccion Fisica");

        jLabel5.setText("Direccion Fiscal");

        jLabel6.setText("Telefono");

        jLabel7.setText("Pagina Web");

        jbtnRegistroCLienteJuridico.setText("Registrar");

        jLabel14.setText("Estado:");

        jLabel15.setText("Municipio:");

        jLabel16.setText("Parroquia:");

        jLabel17.setText("Estado:");

        jLabel18.setText("Municipio:");

        jLabel19.setText("Parroquia:");

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("(*)");

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("(*)");

        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("(*)");

        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("(*)");

        lblErrorRegistoClienteJuridicoDenominacionComercial.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoDenominacionComercial.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteJuridicoRazonSocial.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoRazonSocial.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteJuridicoRif.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoRif.setText("Error, Igresar caracteres alfanumericos");

        lblErrorRegistoClienteJuridicoTelefono.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoTelefono.setText("Error, Telefono incorrecto");

        lblErrorRegistoClienteJuridicoWeb.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorRegistoClienteJuridicoWeb.setText("Error, dirccion web incorrecta");

        jLabel42.setForeground(new java.awt.Color(0, 0, 255));
        jLabel42.setText("(2222)222-2222");

        jLabel43.setForeground(new java.awt.Color(0, 0, 255));
        jLabel43.setText("www.xyz.zxy.xy");

        jbtnRegistroCLienteJuridico1.setText("Consultar");

        jbtnRegistroCLienteJuridico2.setText("Modificar");

        javax.swing.GroupLayout PanelPersonaJuridicaLayout = new javax.swing.GroupLayout(PanelPersonaJuridica);
        PanelPersonaJuridica.setLayout(PanelPersonaJuridicaLayout);
        PanelPersonaJuridicaLayout.setHorizontalGroup(
            PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnRegistroCLienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica, 0, 161, Short.MAX_VALUE)
                            .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(438, 438, 438))
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textRegistroCLienteJuridicoRazonSocial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textRegistroCLienteJuridicoRif, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textRegistroCLienteJuridicoTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textRegistroCLienteJuridicoDenominacionComercial)
                            .addComponent(textRegistroCLienteJuridicoUsuario))
                        .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorRegistoClienteJuridicoRazonSocial))
                                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorRegistoClienteJuridicoDenominacionComercial))
                                    .addComponent(jLabel42)
                                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel43))
                                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorRegistoClienteJuridicoRif))))
                            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorRegistoClienteJuridicoWeb)
                                    .addComponent(lblErrorRegistoClienteJuridicoTelefono)))))
                    .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                        .addComponent(jbtnRegistroCLienteJuridico1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRegistroCLienteJuridico2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelPersonaJuridicaLayout.setVerticalGroup(
            PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaJuridicaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textRegistroCLienteJuridicoDenominacionComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(lblErrorRegistoClienteJuridicoDenominacionComercial))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textRegistroCLienteJuridicoRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(lblErrorRegistoClienteJuridicoRazonSocial))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textRegistroCLienteJuridicoRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(lblErrorRegistoClienteJuridicoRif))
                .addGap(20, 20, 20)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textRegistroCLienteJuridicoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorRegistoClienteJuridicoTelefono)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel22)
                    .addComponent(lblErrorRegistoClienteJuridicoWeb)
                    .addComponent(jLabel43)
                    .addComponent(textRegistroCLienteJuridicoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PanelPersonaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegistroCLienteJuridico)
                    .addComponent(jbtnRegistroCLienteJuridico1)
                    .addComponent(jbtnRegistroCLienteJuridico2))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jScrollPanePersonaJuridica.setViewportView(PanelPersonaJuridica);

        jTabbedPaneRegistroCliente.addTab("Proveedor", jScrollPanePersonaJuridica);

        jtbtnRegistroCLienteVolver.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblRegistroCLienteTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jtbtnRegistroCLienteVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblRegistroCLienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbtnRegistroCLienteVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneRegistroCliente.getAccessibleContext().setAccessibleName("CLiente");
        jTabbedPaneRegistroCliente.getAccessibleContext().setAccessibleDescription("Valido para clientes ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setRegistroClienteController(RegistroClienteController c){
          //Botones  
            jtbtnRegistroCLienteVolver.addActionListener(c);
            jbtnRegistroCLienteJuridico.addActionListener(c);
            
            //Text Field
                       //Juridico
                    
                     textRegistroCLienteJuridicoDenominacionComercial.addActionListener(c);
                     textRegistroCLienteJuridicoRazonSocial.addActionListener(c);
                    
                     textRegistroCLienteJuridicoRif.addActionListener(c);
                     textRegistroCLienteJuridicoTelefono.addActionListener(c);
                     textRegistroCLienteJuridicoUsuario.addActionListener(c);
                     
                     //Natural
                   
                     //Combobox
                         jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal.addActionListener(c);
                        jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica.addActionListener(c);
                        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal.addActionListener(c);
                        jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica.addActionListener(c);
                         jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal.addActionListener(c);
                          jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica.addActionListener(c);
                        
        
    }
    public void MustraRegisroCliente (){
               lblErrorRegistoClienteJuridicoDenominacionComercial.setVisible(false);
                lblErrorRegistoClienteJuridicoRazonSocial.setVisible(false);
               lblErrorRegistoClienteJuridicoRif.setVisible(false);
               lblErrorRegistoClienteJuridicoTelefono.setVisible(false);
               lblErrorRegistoClienteJuridicoWeb.setVisible(false);
             
             //   lblErrorRegistoClienteNaturalEmail3.setVisible(false);
                
           
                
                setTitle("Bienvenido");
		setResizable(false);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLocationRelativeTo(null);
		setVisible(true);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPersonaJuridica;
    private javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoEstadoDireccionFiscal;
    private javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoEstadoDireccionFisica;
    private javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoMunicipioDireccionFiscal;
    private javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoMunicipioDireccionFisica;
    private javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoParroquiaDireccionFiscal;
    private javax.swing.JComboBox jComboBoxRegistroCLienteJuridicoParroquiaDireccionFisica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JScrollPane jScrollPanePersonaJuridica;
    private javax.swing.JTabbedPane jTabbedPaneRegistroCliente;
    private javax.swing.JButton jbtnRegistroCLienteJuridico;
    public javax.swing.JButton jbtnRegistroCLienteJuridico1;
    public javax.swing.JButton jbtnRegistroCLienteJuridico2;
    private javax.swing.JLabel jlblRegistroCLienteTitulo;
    public javax.swing.JButton jtbtnRegistroCLienteVolver;
    private javax.swing.JLabel lblErrorRegistoClienteJuridicoDenominacionComercial;
    private javax.swing.JLabel lblErrorRegistoClienteJuridicoRazonSocial;
    private javax.swing.JLabel lblErrorRegistoClienteJuridicoRif;
    private javax.swing.JLabel lblErrorRegistoClienteJuridicoTelefono;
    private javax.swing.JLabel lblErrorRegistoClienteJuridicoWeb;
    private javax.swing.JTextField textRegistroCLienteJuridicoDenominacionComercial;
    private javax.swing.JTextField textRegistroCLienteJuridicoRazonSocial;
    private javax.swing.JTextField textRegistroCLienteJuridicoRif;
    private javax.swing.JTextField textRegistroCLienteJuridicoTelefono;
    private javax.swing.JTextField textRegistroCLienteJuridicoUsuario;
    // End of variables declaration//GEN-END:variables
}
